### ISSUE TITLE
Request for Detailed Training Process

### ISSUE THREAD

**Issue by ZZC9965** [xzluo97/Continual-Reg#1]
Dear luo,

I hope this message finds you well.

I am writing to seek clarification regarding the training process that was provided earlier. After reviewing the materials, I realize that I do not fully understand certain aspects of the process.

Could you please provide a more detailed explanation or any additional resources that could help clarify the steps involved? A comprehensive breakdown of the training process would be greatly appreciated to ensure that I am able to follow it accurately and effectively.

Thank you very much for your assistance. I look forward to your response.

Best regards,
ZZC

**Comment by xzluo97** [comment]
Hi ZZC, 

Thank you for contacting me.

To train the model, the first step would be installing the package [deep_kit](https://github.com/xzluo97/deep_kit/tree/dev), which contains the code for setting up the optimizer and the training pipeline.

Next, modify the root path of the training dataset in this [line](https://github.com/xzluo97/Continual-Reg/blob/9076cf9f1078e2ad9ad634b2bbd9c52c53db3e24/core/datasets/continual3d.py#L19). Make sure your datasets are structured the same as what is described in the comments of the data providers in `./core/data/data_providers`.

Then, you should be able to start training by step 4 in [Usage](https://github.com/xzluo97/Continual-Reg/tree/main?tab=readme-ov-file#usage).

If you have any further questions, please feel free to contact me.

Best, 
Xinzhe
