### ISSUE TITLE
缺少intensity_augment.py

### ISSUE THREAD

**Issue by kekukin** [xzluo97/Continual-Reg#3]
不能在core/data/找到intensity_augment文件。
from core.data.intensity_augment import randomIntensityFilter

**Comment by xzluo97** [comment]
intensity_augment.py has been uploaded.

**Comment by xzluo97** [comment]
> intensity_augment.py has been uploaded.

We didn't use intensity augmentation during training, but you can try it yourself.

**Comment by kekukin** [comment]
谢谢您的回复，已经看到了
